language: go
dist: precise
go:
  - 1.9.3
  - tip
os:
  - linux
  - osx
env:
  - DEP_VERSION="0.4.1"
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - dep ensure
script:
  - go test ./...
before_install:
  - mkdir -p $GOPATH/bin
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
