language: go
dist: precise
go:
  - 1.9.3
  - tip
os:
  - linux
  - osx
env:
  - DEP_VERSION="0.4.1"
matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - $GOPATH/bin/dep ensure
script:
  - go test $(go list ./... | grep -v '/vendor/')
before_install:
  - mkdir -p $GOPATH/bin
  - go get -u github.com/golang/dep/cmd/dep
  - chmod +x $GOPATH/bin/dep
